# Site settings
title: "Nichole Dugan"
email: ndugan@gmail.com
description: "A blog documenting our journey to AWS"
baseurl: ""
url: "http://ndugan.github.io"
title_description: "Get thee to the Cloud!"
title_image: "/assets/img/ndugan.png"
google_analytics: 
disqus_account: 
github_repository: https://github.com/ndugan
addthis_id: 
post_limit: 10

defaults:
  - scope:
     path: "assets/img"
    values:
     image: true

# Social usernames/URLs
twitter_username: 
github_username:  ndugan
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/nichole-dugan
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: 
footer_right: "<a href=\"https://github.com/ndugan\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
